# Sequoia Sequoia Retro Light for tmux
set -g @dracula-theme 'sequoia-retro-light'
set -g status-style 'bg=#edeef2,fg=#282930'
set -g status-left-style 'bg=#e2e3e8,fg=#282930'
set -g status-right-style 'bg=#e2e3e8,fg=#42434e'
set -g window-status-current-style 'bg=#8a6539,fg=#0f1014,bold'
set -g window-status-style 'bg=#edeef2,fg=#42434e'
set -g message-style 'bg=#e2e3e8,fg=#282930'
set -g pane-border-style 'fg=#42434e'
set -g pane-active-border-style 'fg=#8a6539'
set -g @dracula-color0 '#d4d5dc'
set -g @dracula-color1 '#5f7982'
set -g @dracula-color2 '#4a704e'
set -g @dracula-color3 '#bf5238'
set -g @dracula-color4 '#456a82'
set -g @dracula-color5 '#c99730'
set -g @dracula-color6 '#8a6539'
set -g @dracula-color7 '#282930'
set -g @dracula-color8 '#42434e'
set -g @dracula-color9 '#c99730'
set -g @dracula-color10 '#4a704e'
set -g @dracula-color11 '#bf5238'
set -g @dracula-color12 '#456a82'
set -g @dracula-color13 '#5f7982'
set -g @dracula-color14 '#8a6539'
set -g @dracula-color15 '#282930'
