# Sequoia Sequoia Monochrome Light for tmux
set -g @dracula-theme 'sequoia-monochrome-light'
set -g status-style 'bg=#edeef2,fg=#282930'
set -g status-left-style 'bg=#e2e3e8,fg=#282930'
set -g status-right-style 'bg=#e2e3e8,fg=#42434e'
set -g window-status-current-style 'bg=#454752,fg=#0f1014,bold'
set -g window-status-style 'bg=#edeef2,fg=#42434e'
set -g message-style 'bg=#e2e3e8,fg=#282930'
set -g pane-border-style 'fg=#42434e'
set -g pane-active-border-style 'fg=#454752'
set -g @dracula-color0 '#d4d5dc'
set -g @dracula-color1 '#525666'
set -g @dracula-color2 '#2e3038'
set -g @dracula-color3 '#50535e'
set -g @dracula-color4 '#5f6370'
set -g @dracula-color5 '#25262d'
set -g @dracula-color6 '#454752'
set -g @dracula-color7 '#282930'
set -g @dracula-color8 '#42434e'
set -g @dracula-color9 '#525666'
set -g @dracula-color10 '#2e3038'
set -g @dracula-color11 '#50535e'
set -g @dracula-color12 '#5f6370'
set -g @dracula-color13 '#25262d'
set -g @dracula-color14 '#454752'
set -g @dracula-color15 '#282930'
