# Sequoia Sequoia Monochrome Dark for tmux
set -g @dracula-theme 'sequoia-monochrome-dark'
set -g status-style 'bg=#0f1014,fg=#868690'
set -g status-left-style 'bg=#111216,fg=#868690'
set -g status-right-style 'bg=#111216,fg=#575861'
set -g window-status-current-style 'bg=#b6bac8,fg=#0f1014,bold'
set -g window-status-style 'bg=#0f1014,fg=#575861'
set -g message-style 'bg=#111216,fg=#868690'
set -g pane-border-style 'fg=#575861'
set -g pane-active-border-style 'fg=#b6bac8'
set -g @dracula-color0 '#131317'
set -g @dracula-color1 '#999eb2'
set -g @dracula-color2 '#626983'
set -g @dracula-color3 '#d3d5de'
set -g @dracula-color4 '#7c829d'
set -g @dracula-color5 '#e2e4ed'
set -g @dracula-color6 '#b6bac8'
set -g @dracula-color7 '#868690'
set -g @dracula-color8 '#575861'
set -g @dracula-color9 '#999eb2'
set -g @dracula-color10 '#626983'
set -g @dracula-color11 '#d3d5de'
set -g @dracula-color12 '#7c829d'
set -g @dracula-color13 '#e2e4ed'
set -g @dracula-color14 '#b6bac8'
set -g @dracula-color15 '#868690'
