# Sequoia Sequoia Retro Dark for tmux
set -g @dracula-theme 'sequoia-retro-dark'
set -g status-style 'bg=#0f1014,fg=#868690'
set -g status-left-style 'bg=#111216,fg=#868690'
set -g status-right-style 'bg=#111216,fg=#575861'
set -g window-status-current-style 'bg=#a27e57,fg=#0f1014,bold'
set -g window-status-style 'bg=#0f1014,fg=#575861'
set -g message-style 'bg=#111216,fg=#868690'
set -g pane-border-style 'fg=#575861'
set -g pane-active-border-style 'fg=#a27e57'
set -g @dracula-color0 '#131317'
set -g @dracula-color1 '#829fa7'
set -g @dracula-color2 '#648f68'
set -g @dracula-color3 '#da674b'
set -g @dracula-color4 '#5c87a4'
set -g @dracula-color5 '#e8b246'
set -g @dracula-color6 '#a27e57'
set -g @dracula-color7 '#868690'
set -g @dracula-color8 '#575861'
set -g @dracula-color9 '#e8b246'
set -g @dracula-color10 '#648f68'
set -g @dracula-color11 '#da674b'
set -g @dracula-color12 '#5c87a4'
set -g @dracula-color13 '#829fa7'
set -g @dracula-color14 '#a27e57'
set -g @dracula-color15 '#868690'
